### ISSUE TITLE
Updates are failing with failed to parse transport header

### ISSUE THREAD

**Issue by cdw-brendenmorgenthaler** [doksu/TA-asngen#9]
Yesterday ASN Generator worked in our test environment.  Today I tried to install in our prod environment and it would not generate any output.  Delving into it from the command line and running the code manually as splunk user return "Failed to parse transport header" in both environments.

``` $SPLUNK_HOME/bin/splunk cmd python /opt/splunk/etc/apps/TA-asngen/bin/asngen.py```
```chunked 1.0,203,0
{"finished":true,"inspector":{"messages":[["ERROR","RuntimeError at \"/opt/splunk/etc/apps/TA-asngen/bin/splunklib/searchcommands/search_command.py\", line 857 : Failed to parse transport header: \n"]]}}
```

**Comment by bekirk** [comment]
Same problem here I need my ASN's back :-(

**Comment by KaterinaKop** [comment]
The same problem(

**Comment by ymylei** [comment]
Hey Y'all,

I think running these commands from the command line is not going to be a decent test, since I assume there's Splunk libraries and stuff missing when you do that. 

I've had the same (or very) similar issue where "| asngen" would not output any data. Based on my testing (and pull request which followed), this is because of when the "yield loop" is occurring and the ordering of the files within the ZIP. 

If you do the same modification I'm suggesting in #10, then you should have output once again.

**Comment by doksu** [comment]
Thanks very much everyone for letting me know and @ymylei for providing a patch. Version 1.0.1 is now available on Splunkbase: https://splunkbase.splunk.com/app/3531/
